trigger:
  branches:
    include:
    - master

strategy:
  matrix:
    mac_35:
      imageName: 'macOS-10.13'
      python.version: '3.x'
    mac_36:
      imageName: 'macOS-10.13'
      python.version: '3.x'
    mac_37:
      imageName: 'macOS-10.13'
      python.version: '3.x'
    linux_py35:
      imageName: 'ubuntu-16.04'
      python.version: '3.5'
    linux_py36:
      imageName: 'ubuntu-16.04'
      python.version: '3.6'
    linux_py37:
      imageName: 'ubuntu-16.04'
      python.version: '3.7'
  maxParallel: 4

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: python -m pip install --upgrade black
  displayName: 'Install black (linter)'
  condition: eq(variables['python.version'], '3.7')
- script: black --check .
  displayName: 'Test Formating'
  condition: eq(variables['python.version'], '3.7')
 
- script: python -m pip install --upgrade .
  displayName: 'Test Install'
  condition: ne(variables['Agent.OS'], 'Windows_NT')

- bash: |
    set -xeo pipefail
    # Display log files if the build failed
    echo "Dumping log files for failed build"
    echo "----------------------------------"
    for f in $(find $BUILD_REPOSITORY_LOCALPATH/build -name *.log);
      do echo "------"
         echo $f
         echo "======"
         cat $f
      done;
  condition: failed() # only run this job if the build step failed
  displayName: "Print log files (failed build only)"
